---
name: ansible-release

on:
  workflow_call:
    secrets:
      AUTOMATION_PAT:
        required: true

permissions:
  contents: read

concurrency:
  group: release-${{ github.repository }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.AUTOMATION_PAT }}
          release-type: simple

      - name: Install dependencies
        run: pip3 install ansible-core

      - name: Import role into Galaxy
        run: ansible-galaxy role import --api-key ${{ secrets.GALAXY_API_KEY }} $(echo ${{ github.repository }} | cut -d/ -f1) $(echo ${{ github.repository }} | cut -d/ -f2)
