---
name: renovate

on:
  workflow_call:
    secrets:
      AUTOMATION_PAT:
        required: true

concurrency:
  group: renovate-${{ github.repository }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.AUTOMATION_PAT }}

      - name: Renovate
        uses: renovatebot/github-action@v44.2.3
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
        with:
          token: ${{ secrets.AUTOMATION_PAT }}
